site_name: MorphUI

theme:
  name: material
  custom_dir: overrides
  # logo: img/logo_w.ico
  # favicon: img/logo.ico
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: teal
      accent: amber

  features:
  - search.suggest
  - search.highlight
  - content.tabs.link
  - navigation.indexes
  - content.tooltips
  - navigation.path
  - content.code.annotate
  - content.code.copy
  - content.code.select
  - navigation.tabs

repo_name: j4ggr/MorphUI
repo_url: https://github.com/j4ggr/MorphUI

plugins: 
  search: null
  mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: numpy
          docstring_section_style: list
          heading_level: 1
          merge_init_into_class: false
          show_bases: true
          show_source: false
          show_root_heading: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          show_docstring_functions: true
          inherited_members: true
          members_order: alphabetical
          group_by_category: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
    
extra_css:
  - css/custom-colors.css

nav:
  - Home:
    - MorphUI: index.md
    - Changelog: CHANGELOG.md
  - User Guide:
    - guides/index.md
  - Components:
    - Button: components/button.md
    - Chip: components/chip.md
    - Dialog: components/dialog.md
    - Divider: components/divider.md
    - Dropdown: components/dropdown.md
    - Label: components/label.md
    - List: components/list.md
    - Menu: components/menu.md
    - Progress: components/progress.md
    - Selection: components/selection.md
    - Text Field: components/textfield.md
    - Tooltip: components/tooltip.md
  - Layouts:
    - Anchor Layout: layouts/anchorlayout.md
    - Box Layout: layouts/boxlayout.md
    - Container: layouts/container.md
    - Float Layout: layouts/floatlayout.md
    - Grid Layout: layouts/gridlayout.md
    - Recycle Box Layout: layouts/recycleboxlayout.md
    - Recycle Grid Layout: layouts/recyclegridlayout.md
    - Recycle View: layouts/recycleview.md
    - Relative Layout: layouts/relativelayout.md
    - Screen Manager: layouts/screenmanager.md
    - Scroll View: layouts/scrollview.md
    - Stack Layout: layouts/stacklayout.md
    - Widget: layouts/widget.md
  - Data View:
    - Base: dataview/base.md
    - Header: dataview/header.md
    - Index: dataview/index.md
    - Body: dataview/body.md
    - Navigation: dataview/navigation.md
    - Table: dataview/table.md
  - Pickers:
    - Date Picker: pickers/datepicker.md
  - Visualization:
    - Chart: visualization/chart.md
    - Plotting: visualization/plotting.md
  - API:
    - api/index.md