site_name: MorphUI

theme:
  name: material
  custom_dir: overrides
  # logo: img/logo_w.ico
  # favicon: img/logo.ico
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: teal
      accent: amber

  features:
  - search.suggest
  - search.highlight
  - content.tabs.link
  - navigation.indexes
  - content.tooltips
  - navigation.path
  - content.code.annotate
  - content.code.copy
  - content.code.select
  - navigation.tabs

repo_name: j4ggr/MorphUI
repo_url: https://github.com/j4ggr/MorphUI

plugins: 
  search: null
  mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: numpy
          docstring_section_style: list
          heading_level: 1
          merge_init_into_class: false
          show_bases: true
          show_source: false
          show_root_heading: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          show_docstring_functions: true
          inherited_members: true
          members_order: alphabetical
          group_by_category: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
    
extra_css:
  - css/custom-colors.css

nav:
  - Home: 
    - MorphUI: index.md
    - Changelog: CHANGELOG.md
  - User Guide:
    - guides/index.md
  - API:
    - api/index.md